#!/bin/bash

# Navigate to the directory where your Python script is located
cd /home/ubuntu/ansible

# Run the Python script, display its output, and also capture it to a temporary file
python3 generate_remove_playbook.py | tee /tmp/script_output.txt
# Capture file name generated by the Python script
filename=$(cat /tmp/python_script_output.txt)
echo "$filename"
# Check if filename was captured and exists then run the Ansible playbook
if [[ -n "$filename" && -f "/home/ubuntu/ansible/users/$filename" ]]; then
    echo "Running Ansible playbook: $filename"
    cd /home/ubuntu/ansible/
    ansible-playbook "users/$filename"
else
    echo "Could not find the Ansible playbook file. Exiting."
    exit 1
fi
cd /home/ubuntu/ansible/users
rm $filename
cd
# Cleanup
rm /tmp/python_script_output.txt
